Repository cse110-fall21-group9/Digital-Cookbook-App, pull requests merged in 2021-12, with the labels that each got.

#34 Add ci builds
  .github/workflows/build.yml
  assets/scripts/main.js
  buildall.sh
  package-lock.json
  package.json
  release-package.json
Labels: CI/CD, deployment, high priority

#42 Add unit tests for IOSystem
  __tests__/IOSystem.test.js
  __tests__/ex.test.js
Labels: CI/CD, testing, high priority

#43 Fix Default Img
  assets/images/Movies.png
  assets/images/logarithm-rules.png
  assets/scripts/app.js
  assets/scripts/main.js
  index.html
Labels: bug, frontend

#65 Updated readme
  README.md
Labels: documentation

#74 Add auto docs gen
  .github/workflows/docs.yml
  package-lock.json
  package.json
Labels: documentation, CI/CD

#71 Update Docs
  README.md
  assets/scripts/main.js
  assets/scripts/preload.js
Labels: documentation

#75 Cleanup ci scripts
  .github/workflows/build.yml
  ci/buildall.sh
  ci/install.sh
  ci/release-package.json
  ci/run.sh
Labels: CI/CD, deployment

#79 Add export functionality
  assets/images/food-tablle.jpg
  assets/scripts/IOSystem.js
  assets/scripts/app.js
  assets/scripts/main.js
  assets/scripts/preload.js
  assets/scripts/recipeCard.js
  index.html
Labels: backend, frontend, high priority

#80 Fixed the style for Import/Export
  assets/scripts/recipeCard.js
  index.html
Labels: frontend

#85 Refactor Spree Complete
  .gitignore
  .vscode/settings.json
  assets/recipes/aaaaaa.json
  assets/recipes/boneSoup.json
  assets/scripts/IOSystem.js
  assets/scripts/app.js
  assets/scripts/main.js
  assets/scripts/preload.js
  assets/scripts/recipeCard.js
  assets/styles/main.css
  index.html
  package-lock.json
  package.json
Labels: bug, enhancement

#89 Build ci fixes
  .github/workflows/build.yml
  ci/buildall.sh
  ci/release-package.json
  package.json
Labels: bug, CI/CD, deployment, high priority

#93 Fix jsdoc
  .github/workflows/build.yml
  .github/workflows/docs.yml
  assets/scripts/IOSystem.js
  assets/scripts/app.js
  assets/scripts/main.js
  assets/scripts/preload.js
  assets/scripts/recipeCard.js
Labels: documentation, enhancement, CI/CD, deployment

#99 Fix ci master
  .github/workflows/build.yml
  .github/workflows/docs.yml
Labels: documentation, CI/CD, deployment

#97 Fixed images not being delet
  assets/recipes/fa854fc5-eb35-4088-bcef-15d5165e6ab7.json
  assets/scripts/main.js
  index.html
Labels: enhancement, deployment

#96 Everyone Add Their Recipes
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .gitignore
  assets/recipes/17d74269-d3c7-4e42-9c6c-e90158263c9b.json
  assets/recipes/2956314e-63fd-4a1f-8cf2-b25c3b70260d.json
  assets/recipes/6724c5d0-b256-468f-a0db-03d77fda109f.json
  assets/recipes/674654ce-c6ca-4b59-867f-571afcb5db0f.json
  assets/recipes/69315e7f-9132-4801-a3ed-e6db805f56f0.json
  assets/recipes/73fe0197-92d8-42a5-88f8-c5654f410704.json
  assets/recipes/8db8bd6b-1c85-4095-8774-a687c8f5e379.json
  assets/recipes/ac00f350-39f7-4bca-b095-f0aec9212739.json
  assets/recipes/c7b4f298-0289-462e-9d10-4b2fb46d5c18.json
  assets/recipes/c8c66d67-52f5-46dc-b044-9f649cc12dac.json
  assets/recipes/c9140cbd-2bf7-4189-9099-56e720fc8fe5.json
  assets/recipes/f7d751f0-2fad-4ccc-bb70-94f1f7b86958.json
  assets/recipes/fa854fc5-eb35-4088-bcef-15d5165e6ab7.json
  assets/recipes/images/ChickpeaCurry.jpg
  assets/recipes/images/Dal-Makhani.jpg
  assets/recipes/images/DuckBroth-e1360852789104.jpg
  assets/recipes/images/Homemade Springrolls.jpeg
  assets/recipes/images/Hot-Honey-Shrimp-Broccoli.webp
  assets/recipes/images/bone-soup.jpg
  assets/recipes/images/chicken_soup.webp
  assets/recipes/images/green-bean-casserole.jpeg
  assets/recipes/images/grilledCheese.jpg
  assets/recipes/images/hummus.jpeg
  assets/recipes/images/instant-pot-chicken-dumplings.jpeg
  assets/recipes/images/sugarCookies.jpg
  assets/recipes/images/thai-chicken-curry.jpeg
  assets/scripts/main.js
  index.html
Labels: enhancement, high priority

#98 Update Application Name
  index.html
Labels: enhancement

#100 fix build process
  .github/workflows/build.yml
Labels: CI/CD, deployment

#101 Updated README
  README.md
Labels: bug, CI/CD, deployment
