Repository cse110-fall21-group9/Digital-Cookbook-App, pull requests merged in 2021-11, with the labels that each got.

#25 prettier now ignores CRs
  package.json
Labels: CI/CD

#23 Added ci running tests on push and pr, also in local bash script
  .github/workflows/linter.yml
  .github/workflows/test.yml
  __tests__/ex.test.js
  package-lock.json
  package.json
  run.sh
Labels: CI/CD, testing

#31 Card function implementation
  .gitignore
  assets/images/.DS_Store
  assets/images/burrito.jpeg
  assets/images/cooking.png
  assets/images/search-icon.png
  assets/pages/makeEdit-recipe.html
  assets/pages/view-recipeCard.html
  assets/scripts/IOSystem.js
  assets/scripts/app.js
  assets/scripts/main.js
  assets/scripts/preload.js
  assets/scripts/recipeCard.js
  assets/styles/main.css
  index.html
  package.json
Labels: CI/CD, backend, frontend, deployment, high priority

#35 Fix form size
  assets/scripts/app.js
  assets/styles/main.css
  index.html
Labels: frontend
